import { StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Search, SlidersHorizontal, Users, Clock3, X, WifiOff, ArrowLeft, Image as ImageIcon } from "lucide-react";
import "./styles.css";
import { supabase } from "./supabase";

type Game = { id: string; name: string; category: string | null; min_players: number | null; max_players: number | null; duration_minutes: number | null; min_age: number | null; difficulty: string; notes: string | null; image_url: string | null };
type Filters = { players: string; duration: string; difficulty: string; age: string; category: string };
const CACHE_KEY = "terraludo-public-games-v2";
const GAME_FIELDS = "id,name,category,min_players,max_players,duration_minutes,min_age,difficulty,notes,image_url";
const CATEGORIES = ["Cartas", "Cooperativo", "Dados", "Estrategia", "Estrategia Abstracta", "Estrategia Ligera", "Fiesta", "Roles Ocultos", "Temático"];
const emptyFilters: Filters = { players: "", duration: "", difficulty: "", age: "", category: "" };

async function loadGames(): Promise<Game[]> {
  try {
    const { data, error } = await supabase.from("board_games").select(GAME_FIELDS).order("name", { ascending: true });
    if (error) throw error;
    const games = (data ?? []) as Game[]; localStorage.setItem(CACHE_KEY, JSON.stringify(games)); return games;
  } catch { const cached = localStorage.getItem(CACHE_KEY); return cached ? JSON.parse(cached) as Game[] : []; }
}
async function loadGameById(id: string): Promise<Game | null> {
  try { const { data, error } = await supabase.from("board_games").select(GAME_FIELDS).eq("id", id).maybeSingle(); if (error) throw error; return data as Game | null; }
  catch { const cached = localStorage.getItem(CACHE_KEY); return cached ? (JSON.parse(cached) as Game[]).find((game) => String(game.id) === String(id)) ?? null : null; }
}
function getGameIdFromUrl() { const match = window.location.hash.match(/^#\/game\/([^/]+)$/); return match ? decodeURIComponent(match[1]) : null; }

function App() {
  const [games, setGames] = useState<Game[]>([]); const [query, setQuery] = useState(""); const [filters, setFilters] = useState<Filters>(emptyFilters); const [showFilters, setShowFilters] = useState(false); const [isOffline, setIsOffline] = useState(!navigator.onLine);
  const [selectedId, setSelectedId] = useState<string | null>(getGameIdFromUrl()); const [selectedGame, setSelectedGame] = useState<Game | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState<string | null>(null);
  useEffect(() => { loadGames().then(setGames); const handleOnline = () => setIsOffline(false); const handleOffline = () => setIsOffline(true); const routeChanged = () => setSelectedId(getGameIdFromUrl()); window.addEventListener("online", handleOnline); window.addEventListener("offline", handleOffline); window.addEventListener("hashchange", routeChanged); return () => { window.removeEventListener("online", handleOnline); window.removeEventListener("offline", handleOffline); window.removeEventListener("hashchange", routeChanged); }; }, []);
  useEffect(() => { if (!selectedId) { setSelectedGame(null); setDetailError(null); setDetailLoading(false); return; } let cancelled = false; const cachedGame = games.find((game) => String(game.id) === String(selectedId)) ?? null; setSelectedGame(cachedGame); setDetailLoading(true); setDetailError(null); loadGameById(selectedId).then((game) => { if (cancelled) return; setSelectedGame(game ?? cachedGame); if (!game && !cachedGame) setDetailError("No se encontró este juego en la base de datos pública."); setDetailLoading(false); }).catch(() => { if (cancelled) return; if (!cachedGame) setDetailError("No se pudo cargar la información del juego."); setDetailLoading(false); }); return () => { cancelled = true; }; }, [selectedId, games]);
  const filteredGames = useMemo(() => { const q = query.trim().toLocaleLowerCase(); const players = filters.players ? Number(filters.players) : null; return games.filter((game) => { if (q && !game.name.toLocaleLowerCase().includes(q)) return false; if (filters.category && game.category !== filters.category) return false; if (players && (game.min_players == null || game.max_players == null || players < game.min_players || players > game.max_players)) return false; if (filters.duration === "short" && (game.duration_minutes == null || game.duration_minutes > 30)) return false; if (filters.duration === "medium" && (game.duration_minutes == null || game.duration_minutes <= 30 || game.duration_minutes > 90)) return false; if (filters.duration === "long" && (game.duration_minutes == null || game.duration_minutes <= 90)) return false; if (filters.difficulty && game.difficulty !== filters.difficulty) return false; if (filters.age && (game.min_age == null || game.min_age > Number(filters.age))) return false; return true; }); }, [games, query, filters]);
  const activeFilters = Object.values(filters).filter(Boolean).length;
  const openGame = (id: string) => { const encodedId = encodeURIComponent(String(id)); setSelectedGame(games.find((game) => String(game.id) === String(id)) ?? null); setSelectedId(String(id)); window.history.pushState({ gameId: String(id) }, "", `${window.location.pathname}${window.location.search}#/game/${encodedId}`); };
  const goHome = () => { setSelectedId(null); setSelectedGame(null); setDetailError(null); setDetailLoading(false); window.history.pushState({}, "", `${window.location.pathname}${window.location.search}`); };
  if (selectedId) return <GameDetail game={selectedGame} loading={detailLoading} error={detailError} onBack={goHome} />;
  return <main className="app"><div className="hero"><div className="brand">🎲 TerraLudo</div><h1>Catálogo de juegos</h1><p>Encuentra el juego perfecto para tu partida.</p>{isOffline && <div className="offline"><WifiOff size={15} /> Modo sin conexión · usando catálogo guardado</div>}</div><section className="search-area"><div className="search-row"><div className="search-box"><Search size={20} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nombre..." aria-label="Buscar juego por nombre" />{query && <button className="icon-button" onClick={() => setQuery("")} aria-label="Limpiar búsqueda"><X size={18} /></button>}</div><button className={"filter-button " + (showFilters || activeFilters ? "active" : "")} onClick={() => setShowFilters(!showFilters)}><SlidersHorizontal size={18} /> Filtros {activeFilters ? `(${activeFilters})` : ""}</button></div>{showFilters && <div className="filters"><label>Categoría<select value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })}><option value="">Cualquiera</option>{CATEGORIES.map(category => <option key={category} value={category}>{category}</option>)}</select></label><label>Jugadores<select value={filters.players} onChange={(e) => setFilters({ ...filters, players: e.target.value })}><option value="">Cualquiera</option>{[1,2,3,4,5,6,7,8,10].map(n => <option key={n} value={n}>{n} jugadores</option>)}</select></label><label>Duración<select value={filters.duration} onChange={(e) => setFilters({ ...filters, duration: e.target.value })}><option value="">Cualquiera</option><option value="short">Hasta 30 min</option><option value="medium">31–90 min</option><option value="long">Más de 90 min</option></select></label><label>Dificultad<select value={filters.difficulty} onChange={(e) => setFilters({ ...filters, difficulty: e.target.value })}><option value="">Cualquiera</option><option value="casual">Casual</option><option value="medium">Medio</option><option value="hard">Difícil</option><option value="expert">Experto</option></select></label><label>Edad máxima<select value={filters.age} onChange={(e) => setFilters({ ...filters, age: e.target.value })}><option value="">Cualquiera</option>{[6,8,10,12,14,16,18].map(n => <option key={n} value={n}>{n}+ recomendado</option>)}</select></label>{activeFilters > 0 && <button className="clear" onClick={() => setFilters(emptyFilters)}>Limpiar filtros</button>}</div>}</section><section className="results"><div className="results-header"><strong>{filteredGames.length}</strong> {filteredGames.length === 1 ? "juego" : "juegos"}</div>{filteredGames.length === 0 ? <div className="empty">No hay juegos que coincidan con tu búsqueda.</div> : <div className="grid">{filteredGames.map(game => <GameCard key={game.id} game={game} onOpen={openGame} />)}</div>}</section></main>;
}

function GameCard({ game, onOpen }: { game: Game; onOpen: (id: string) => void }) { const difficulty = ({ casual: "Casual", medium: "Medio", hard: "Difícil", expert: "Experto" } as Record<string,string>)[game.difficulty] ?? game.difficulty; return <button type="button" className="card card-button" onClick={() => onOpen(game.id)} aria-label={`Ver detalles de ${game.name}`}>{game.image_url && <img className="card-image" src={game.image_url} alt="" />}<div className="card-title"><h2>{game.name}</h2><span className={`difficulty ${game.difficulty}`}>{difficulty}</span></div><div className="category-row">{game.category && <span className="category-badge">{game.category}</span>}</div><div className="meta">{game.min_players != null && game.max_players != null && <span><Users size={16} /> {game.min_players}–{game.max_players}</span>}{game.duration_minutes != null && <span><Clock3 size={16} /> {game.duration_minutes} min</span>}{game.min_age != null && <span>Edad {game.min_age}+</span>}</div>{game.notes && <p>{game.notes}</p>}<span className="card-link">Ver detalles →</span></button>; }

function GameDetail({ game, loading, error, onBack }: { game: Game | null; loading: boolean; error: string | null; onBack: () => void }) { const difficulty = game ? (({ casual: "Casual", medium: "Medio", hard: "Difícil", expert: "Experto" } as Record<string,string>)[game.difficulty] ?? game.difficulty) : ""; return <main className="detail-page"><div className="detail-shell"><button type="button" className="back-button" onClick={onBack}><ArrowLeft size={18} /> Volver al catálogo</button>{loading && !game ? <div className="detail-card detail-message"><h1>Cargando juego…</h1><p>Estamos obteniendo la información desde el catálogo.</p></div> : error && !game ? <div className="detail-card detail-message"><h1>No se pudo cargar</h1><p>{error}</p></div> : game ? <article className="detail-card"><div className="detail-media">{game.image_url ? <img src={game.image_url} alt={`Foto de ${game.name}`} className="detail-image" /> : <><ImageIcon size={54} /><span>Foto del juego</span><small>La imagen se añadirá aquí</small></>}</div><div className="detail-content"><div className="detail-tags">{game.category && <span className="category-badge">{game.category}</span>}<span className={`difficulty ${game.difficulty}`}>{difficulty}</span></div><h1>{game.name}</h1>{game.notes && <section><h2>Descripción</h2><p className="description">{game.notes}</p></section>}<section><h2>Información del juego</h2><div className="detail-grid">{game.category && <div><span>Categoría</span><strong>{game.category}</strong></div>}{game.min_players != null && game.max_players != null && <div><span>Jugadores</span><strong><Users size={17} /> {game.min_players}–{game.max_players}</strong></div>}{game.duration_minutes != null && <div><span>Duración</span><strong><Clock3 size={17} /> {game.duration_minutes} min</strong></div>}{game.min_age != null && <div><span>Edad mínima</span><strong>{game.min_age}+</strong></div>}<div><span>Dificultad</span><strong>{difficulty}</strong></div></div></section></div></article> : null}</div></main>; }

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
